### ISSUE TITLE
Proposal: Migrating to Next.js for Enhanced SEO

### ISSUE THREAD

**Issue by hismethod** [lukasjhan/sd-jwt-io#2]
Hey Lukas, Thanks for starting this project!
Given the importance of SEO for the app, I suggest considering a switch to Next.js
I’m ready to tackle the migration and will prepare a PR for your review soon.

**Comment by lukasjhan** [comment]
Sounds good.

**Comment by lukasjhan** [comment]
@hismethod 
Unfortunately, the code mirror does not work properly in next js, and I failed to find a solution.
