### ISSUE TITLE
Rename Section Titles for Encoder/Decoder Modes

### ISSUE THREAD

**Issue by hismethod** [lukasjhan/sd-jwt-io#31]
Proposing to rename section titles for clarity:

- Encoder mode: "Encoded" / "Decoded" to "Encoded" / "Result"
- Decoder mode: "Decoded" / "Encoded" to "Raw" / "Result"

**Comment by lukasjhan** [comment]
@hismethod I think the term `Result` and `Raw` is ambiguous.

The term `Result` represents the decoding results from encoded credentials.
I don't understand the term `Raw` represents. 

I think it's better to follow the UX in jwt.io. It's a more familiar way

**Comment by lukasjhan** [comment]
If you think the current terms are not clear enough, I propose to change our modes into `issue`, `present` and `verify`

**Comment by lukasjhan** [comment]
@yunseorim1116 Can you share your thoughts?

**Comment by yunseorim1116** [comment]
I feel like it's really hard to redefine terms to make it easier for everyone to use. 
I think it's best to follow the terminology on JWT's site as closely as possible. The term Raw is a bit unfamiliar to me.
How about something like `[Encoded (or Token) | Decode Result ] `?

**Comment by lukasjhan** [comment]
> I feel like it's really hard to redefine terms to make it easier for everyone to use. 
> I think it's best to follow the terminology on JWT's site as closely as possible. The term Raw is a bit unfamiliar to me.
> How about something like `[Encoded (or Token) | Decode Result ] `?

That sounds good to me.

**Comment by lukasjhan** [comment]
1st, For right section: `[Encoded | Decoded] Result`
