### ISSUE TITLE
Scrollbar Appeared in Textarea

### ISSUE THREAD

**Issue by hismethod** [lukasjhan/sd-jwt-io#35]
A scrollbar popped up in the textarea out of nowhere.

It makes the area awkward. Can you check this out? @yunseorim1116 

<img width="625" alt="image" src="https://github.com/lukasjhan/sd-jwt-io/assets/8022624/53067a21-5042-4237-aaef-f497a20134c7">

**Comment by lukasjhan** [comment]
Maybe it's due to my PR. There is no scollbar yesterday

**Comment by lukasjhan** [comment]
I find the cause @yunseorim1116 

feat: add mobile layout (#33)

**Comment by lukasjhan** [comment]
PR is up in #36
